export const sampleAllCards = {
  "0": {
    id: 0,
    category: "Brawn",
    name: "Vitamins",
    description: "15 Health",
    filename: "vitamins.jpg",
  },
  "1": {
    id: 1,
    category: "Brawn",
    name: "Hydration Pack",
    description: "25 Health, -15% Ammo Capacity",
    filename: "hydration-pack.jpg",
  },
  "2": {
    id: 2,
    category: "Brawn",
    name: "Canned Goods",
    description: "40 Health, -30% Stamina",
    filename: "canned-goods.jpg",
  },
  "3": {
    id: 3,
    category: "Brawn",
    name: "Batter Up",
    description: "50% Melee Damage, 5 Health",
    filename: "batter-up.jpg",
  },
  "4": {
    id: 4,
    category: "Brawn",
    name: "Spiky Bits",
    description:
      "25% Melee Damage, 10% Damage Resistance while using a Melee weapon, -15% Ammo Capacity",
    filename: "spiky-bits.jpg",
  },
  "5": {
    id: 5,
    category: "Brawn",
    name: "Mean Drunk",
    description:
      "75% Melee Damage. Your Melee Attacks cleave through enemies dealing damage in a large area. Disables: S",
    filename: "mean-drunk.jpg",
  },
  "6": {
    id: 6,
    category: "Brawn",
    name: "Durable",
    description: "15% Trauma Resistance, 5 Health",
    filename: "durable.jpg",
  },
  "7": {
    id: 7,
    category: "Brawn",
    name: "Body Armor",
    description: "25% Trauma Resistance, -15% Ammo Capacity",
    filename: "body-armor.jpg",
  },
  "8": {
    id: 8,
    category: "Brawn",
    name: "Wooden Armor",
    description:
      "40% Trauma Resistance, -100% Fire Resistance, -100% Acid Resistance, -100% Explosion Resistance",
    filename: "wooden-armor.jpg",
  },
  "9": {
    id: 9,
    category: "Brawn",
    name: "Grenade Training",
    description: "25% Accessory Damage",
    filename: "grenade-training.jpg",
  },
  "10": {
    id: 10,
    category: "Brawn",
    name: "Demolitions Expert",
    description: "50% Accessory Damage, -15% Ammo Capacity",
    filename: "demolitions-expert.jpg",
  },
  "11": {
    id: 11,
    category: "Brawn",
    name: "Improvised Explosives",
    description: "75% Accessory Damage, -25% Swap Speed",
    filename: "improvised-explosives.jpg",
  },
  "12": {
    id: 12,
    category: "Brawn",
    name: "Confident Killer",
    description:
      "When you or your team kills a Mutation gain 1% damage (up to 15% until the end of the level)",
    filename: "confident-killer.jpg",
  },
  "13": {
    id: 13,
    category: "Brawn",
    name: "Heavy Hitter",
    description:
      "Melee hits against Weakspots deal 20 additional Stumble Damage",
    filename: "heavy-hitter.jpg",
  },
  "14": {
    id: 14,
    category: "Brawn",
    name: "Ignore the Pain",
    description:
      "20% Melee Damage against Mutations. When you deal Melee damage to a Mutation gain 1 Temporary Healt",
    filename: "ignore-the pain.jpg",
  },
  "15": {
    id: 15,
    category: "Brawn",
    name: "Berserker",
    description:
      "Gain 10% Melee Damage, 10% Melee Speed, and 5% Move Speed for each Melee kill in the last 4 seconds",
    filename: "berserker.jpg",
  },
  "16": {
    id: 16,
    category: "Brawn",
    name: "True Grit",
    description:
      "When you take a single hit for 15 or more damage, heal 8 Health over 5 seconds",
    filename: "true-grit.jpg",
  },
  "17": {
    id: 17,
    category: "Brawn",
    name: "Pyro",
    description:
      "100% Fire damage. Kill with fire grant you 3 Temporary Health. You can sense flammable objects nearby",
    filename: "pyro.jpg",
  },
  "18": {
    id: 18,
    category: "Brawn",
    name: "Bomb Squad",
    description: "100% Explosive Damage, 35% Explosive Resistance",
    filename: "bomb-squad.jpg",
  },
  "19": {
    id: 19,
    category: "Brawn",
    name: "Scar Tissue",
    description: "Take 1 less damage from all Ridden",
    filename: "scar-tissue.jpg",
  },
  "20": {
    id: 20,
    category: "Brawn",
    name: "Battle Lust",
    description: "Melee Kills heal 2 Health",
    filename: "battle-lust.jpg",
  },
  "21": {
    id: 21,
    category: "Brawn",
    name: "Line 'Em Up",
    description: "100% Bullet Penetration with Assault Rifles",
    filename: "line-'em up.jpg",
  },
  "22": {
    id: 22,
    category: "Brawn",
    name: "Face Your Fears",
    description:
      "Gain 3 Temporary Health whenever you kill a Ridden within 2 meters",
    filename: "face-your fears.jpg",
  },
  "23": {
    id: 23,
    category: "Brawn",
    name: "Well Fed",
    description: "-20% Stamina Regen, Teama Effects: 10 Team Health",
    filename: "well-fed.jpg",
  },
  "24": {
    id: 24,
    category: "Brawn",
    name: "Heavy Attack",
    description:
      "Charge: Hold the attack button with Melee weapons to burst forward. Charge attacks deal 100% incr",
    filename: "heavy-attack.jpg",
  },
  "25": {
    id: 25,
    category: "Brawn",
    name: "Sunder",
    description:
      "Melee hits cause the target to take 20% increased damage for 5 seconds",
    filename: "sunder.jpg",
  },
  "26": {
    id: 26,
    category: "Brawn",
    name: "Overwatch",
    description:
      "Kills from greater than 15 meters grant 5 Temporary Health to teammates within 10 meters of the target",
    filename: "overwatch.jpg",
  },
  "27": {
    id: 27,
    category: "Brawn",
    name: "Fresh Bandage",
    description: "Heal 10 Trauma Damage at the start of each level",
    filename: "fresh-bandage.jpg",
  },
  "28": {
    id: 28,
    category: "Brawn",
    name: "Two is One and One is None",
    description:
      "You can equip a Primary weapon in your Secondary slot. -25% Swap Speed",
    filename: "two-is one and one is none.jpg",
  },
  "29": {
    id: 29,
    category: "Brawn",
    name: "Offensive Scavenger",
    description:
      "You can sense nearby Offensive Accessories, more Offensive Accessories spawn",
    filename: "offensive-scavenger.jpg",
  },
  "30": {
    id: 30,
    category: "Brawn",
    name: "Chemical Courage",
    description: "Pain Meds you apply also grant 25% damage for 60 seconds",
    filename: "chemical-courage.jpg",
  },
  "31": {
    id: 31,
    category: "Brawn",
    name: "Numb ",
    description: "Gain 15% Damage Resistance while you have Temporary Health",
    filename: "numb.jpg",
  },
  "32": {
    id: 32,
    category: "Brawn",
    name: "Broadside ",
    description:
      "Precision Kills have a 20% chance to cause Ridden to explode, dealing 15 damage to other Ridden wit",
    filename: "broadside.jpg",
  },
  "33": {
    id: 33,
    category: "Brawn",
    name: "Buckshot Bruiser",
    description:
      "When using Shotguns, gain Temporary Health for each pellet that hits",
    filename: "buckshot-bruiser.jpg",
  },
  "34": {
    id: 34,
    category: "Brawn",
    name: "Second Chance",
    description: "1 Extra Life, 5 Health",
    filename: "second-chance.jpg",
  },
  "35": {
    id: 35,
    category: "Discipline",
    name: "Ammo Pouch",
    description: "25% Ammo Capacity",
    filename: "ammo-pouch.jpg",
  },
  "36": {
    id: 36,
    category: "Discipline",
    name: "Ammo Belt",
    description: "50% Ammo Capacity, -20% Stamina Efficiency",
    filename: "ammo-belt.jpg",
  },
  "37": {
    id: 37,
    category: "Discipline",
    name: "Ammo Mule",
    description: "75% Ammo Capacity, Disables: Support Accessories",
    filename: "ammo-mule.jpg",
  },
  "38": {
    id: 38,
    category: "Discipline",
    name: "Front Sight Focus",
    description: "20% Accuracy",
    filename: "front-sight focus.jpg",
  },
  "39": {
    id: 39,
    category: "Discipline",
    name: "Optics Enthusiast",
    description: "30% Accuracy, -20% Stamina Efficiency",
    filename: "optics-enthusiast.jpg",
  },
  "40": {
    id: 40,
    category: "Discipline",
    name: "Quick Kill",
    description: "50% Accuracy, Disables: Aim Down Sights",
    filename: "quick-kill.jpg",
  },
  "41": {
    id: 41,
    category: "Discipline",
    name: "Motorcycle Jacket",
    description: "5% Damage Resistance, 5 Health",
    filename: "motorcycle-jacket.jpg",
  },
  "42": {
    id: 42,
    category: "Discipline",
    name: "Padded Suit",
    description: "10% Damage Resistance, 5 Health, -20% Stamina Efficiency",
    filename: "padded-suit.jpg",
  },
  "43": {
    id: 43,
    category: "Discipline",
    name: "Motorcycle Helmet",
    description: "15% Damage Resistance, 10 Health, Disables: Aim Down Sights",
    filename: "motorcycle-helmet.jpg",
  },
  "44": {
    id: 44,
    category: "Discipline",
    name: "Combat Training",
    description: "5% Bullet Damage, 50% Bullet Penetration",
    filename: "combat-training.jpg",
  },
  "45": {
    id: 45,
    category: "Discipline",
    name: "Large Caliber Rounds",
    description:
      "7.5% Bullet Damage, 100% Bullet Penetration, -20% Stamina Efficiency",
    filename: "large-caliber rounds.jpg",
  },
  "46": {
    id: 46,
    category: "Discipline",
    name: "Silver Bullets",
    description:
      "10% Bullet Damage, 150% Bullet Penetration. When you kill a Mutation, you lose 5 Copper",
    filename: "silver-bullets.jpg",
  },
  "47": {
    id: 47,
    category: "Discipline",
    name: "Antibiotic Ointment",
    description: "20% Healing Efficiency",
    filename: "antibiotic-ointment.jpg",
  },
  "48": {
    id: 48,
    category: "Discipline",
    name: "EMT Bag",
    description: "40% Healing Efficiency, -20% Stamina Efficiency",
    filename: "emt-bag.jpg",
  },
  "49": {
    id: 49,
    category: "Discipline",
    name: "Field Surgeon",
    description: "60% Healing Efficiency, -50% Use Speed",
    filename: "field-surgeon.jpg",
  },
  "50": {
    id: 50,
    category: "Discipline",
    name: "Energy Bar",
    description: "20% Stamina Regeneration, 5 Health",
    filename: "energy-bar.jpg",
  },
  "51": {
    id: 51,
    category: "Discipline",
    name: "Cold Brew Coffee",
    description: "40% Stamina Regeneration, -10% Stamina Efficiency",
    filename: "cold-brew coffee.jpg",
  },
  "52": {
    id: 52,
    category: "Discipline",
    name: "Natural Sprinter",
    description: "100% Stamina Regeneration, -50% Maximum Stamina",
    filename: "natural-sprinter.jpg",
  },
  "53": {
    id: 53,
    category: "Discipline",
    name: "Inspiring Sacrifice",
    description:
      "Team Effects: When you or a teammate becomes incapacitated, all teammates heal for 25 Health over 20 se",
    filename: "inspiring-sacrifice.jpg",
  },
  "54": {
    id: 54,
    category: "Discipline",
    name: "Charitable Soul",
    description: "Healing a teammate also applies 50% of the effect to you",
    filename: "charitable-soul.jpg",
  },
  "55": {
    id: 55,
    category: "Discipline",
    name: "Hunker Down",
    description: "While crouching, gain 10% Damage Resistance and 40% Accuracy",
    filename: "hunker-down.jpg",
  },
  "56": {
    id: 56,
    category: "Discipline",
    name: "Avenge the Fallen",
    description:
      "Team Effects: When you or a teammate becomes incapacitated, all teammates gain 30% Damage, 20% Reload S",
    filename: "avenge-the fallen.jpg",
  },
  "57": {
    id: 57,
    category: "Discipline",
    name: "Vanguard",
    description:
      "Melee kills grant 1 Temporary Health to you and nearby teammates",
    filename: "vanguard.jpg",
  },
  "58": {
    id: 58,
    category: "Discipline",
    name: "In the Zone",
    description:
      "Precision Kills grant 5% Reload Speed for 5 seconds (stacking up to 10 times)",
    filename: "in-the zone.jpg",
  },
  "59": {
    id: 59,
    category: "Discipline",
    name: "Trigger Control",
    description: "25% Accuracy with Assault Rifles and Sniper Rifles",
    filename: "trigger-control.jpg",
  },
  "60": {
    id: 60,
    category: "Discipline",
    name: "Needs of the Many",
    description: "-20% Health, Team Effects: 1 Team Extra Life",
    filename: "needs-of the many.jpg",
  },
  "61": {
    id: 61,
    category: "Discipline",
    name: "Combat Knife",
    description: "Turns your Bash into a Knife that counts as a Melee weapon",
    filename: "combat-knife.jpg",
  },
  "62": {
    id: 62,
    category: "Discipline",
    name: "Meatgrinder",
    description:
      "Gain 30% Move Speed and Accuracy while crouched and using an LMG",
    filename: "meatgrinder.jpg",
  },
  "63": {
    id: 63,
    category: "Discipline",
    name: "Scattergun Skills",
    description: "40% Reload Speed with Shotguns",
    filename: "scattergun-skills.jpg",
  },
  "64": {
    id: 64,
    category: "Discipline",
    name: "Controlled Movement",
    description: "40% Move Speed while aiming down sights with Sniper Rifles",
    filename: "controlled-movement.jpg",
  },
  "65": {
    id: 65,
    category: "Discipline",
    name: "Ammo for All",
    description: "Team Effects: 10% Team Ammo Capacity",
    filename: "ammo-for all.jpg",
  },
  "66": {
    id: 66,
    category: "Discipline",
    name: "Down in Front!",
    description:
      "While crouching you neither take nor deal Friendly Fire damage. 10 Health",
    filename: "down-in front!.jpg",
  },
  "67": {
    id: 67,
    category: "Discipline",
    name: "Poultice",
    description:
      "When you use a Medical Accessory, the target heals for an additional 20 Health over 30 seconds",
    filename: "poultice.jpg",
  },
  "68": {
    id: 68,
    category: "Discipline",
    name: "Group Therapy",
    description:
      "When you use a Medical Accessory, all teammates heal for 5 Health",
    filename: "group-therapy.jpg",
  },
  "69": {
    id: 69,
    category: "Discipline",
    name: "Medical Professional",
    description:
      "First Aids and Defibrillators also recover 15 Trauma Damage and 1 Extra Life",
    filename: "medical-professional.jpg",
  },
  "70": {
    id: 70,
    category: "Discipline",
    name: "Ammo Scavenger",
    description: "You can sense nearby Ammo, more Ammo spawns",
    filename: "ammo-scavenger.jpg",
  },
  "71": {
    id: 71,
    category: "Discipline",
    name: "Support Scavenger",
    description:
      "You can sense nearby Support Accessories. More Support Accessories spawn",
    filename: "support-scavenger.jpg",
  },
  "72": {
    id: 72,
    category: "Discipline",
    name: "Weapon Scavenger",
    description: "You can sense nearby weapons. More weapons spawn",
    filename: "weapon-scavenger.jpg",
  },
  "73": {
    id: 73,
    category: "Discipline",
    name: "Amped Up",
    description:
      "When you exit a starting safe room, your team gains 50 Temporary Health",
    filename: "amped-up.jpg",
  },
  "74": {
    id: 74,
    category: "Discipline",
    name: "Patient Hunter",
    description:
      "Each second you Aim Down Sights increases your Damage by 10% (up to 3 stacks)",
    filename: "patient-hunter.jpg",
  },
  "75": {
    id: 75,
    category: "Discipline",
    name: "Power Reload",
    description:
      "Reloading a gun within 0.75 seconds of reaching low ammo will increase its magazine size by 30% unti",
    filename: "power-reload.jpg",
  },
  "76": {
    id: 76,
    category: "Discipline",
    name: "Marked for Death",
    description:
      "Mutations you ping are highlighted and your team deals 10% increased damage to highlighted enemies",
    filename: "marked-for death.jpg",
  },
  "77": {
    id: 77,
    category: "Discipline",
    name: "Knowledge is Power",
    description:
      "10% Weak Spot Damage allows players to see values for damage they deal and enemy health bars",
    filename: "knowledge-is power.jpg",
  },
  "78": {
    id: 78,
    category: "Discipline",
    name: "Tactical Vest",
    description:
      "30% Rifle Ammo Capacity, 10% Damage with Assault Rifles and LMGs",
    filename: "tactical-vest.jpg",
  },
  "79": {
    id: 79,
    category: "Discipline",
    name: "Experienced EMT",
    description:
      "When you use a Medical Accessory, the target gains 20% Maximum Health until the end of the level",
    filename: "experienced-emt.jpg",
  },
  "80": {
    id: 80,
    category: "Fortune",
    name: "Grenade Pouch",
    description: "1 additional Offensive Inventory",
    filename: "grenade-pouch.jpg",
  },
  "81": {
    id: 81,
    category: "Fortune",
    name: "Double Grenade Pouch",
    description: "2 additional Offensive Inventory, -10% Damage Dealt",
    filename: "double-grenade pouch.jpg",
  },
  "82": {
    id: 82,
    category: "Fortune",
    name: "Surplus Pouches",
    description: "-10% Health, +1 Team Offensive Inventory",
    filename: "surplus-pouches.jpg",
  },
  "83": {
    id: 83,
    category: "Fortune",
    name: "Fanny Pack",
    description: "1 additional Support Inventory",
    filename: "fanny-pack.jpg",
  },
  "84": {
    id: 84,
    category: "Fortune",
    name: "Shoulder Bag",
    description: "2 additional Support Inventory, -10% Damage Dealt",
    filename: "shoulder-bag.jpg",
  },
  "85": {
    id: 85,
    category: "Fortune",
    name: "Box O' Bags",
    description: "-10% Health, +1 Team Support Inventory",
    filename: "box-o' bags.jpg",
  },
  "86": {
    id: 86,
    category: "Fortune",
    name: "Mugger",
    description: "Melee kills have a 2% chance to spawn ammo",
    filename: "mugger.jpg",
  },
  "87": {
    id: 87,
    category: "Fortune",
    name: "Highwayman",
    description: "Pistol kills have a 2% chance to spawn ammo",
    filename: "highwayman.jpg",
  },
  "88": {
    id: 88,
    category: "Fortune",
    name: "Admin Reload",
    description: "When you stow your weapon it reloads, -15% Ammo Capacity",
    filename: "admin-reload.jpg",
  },
  "89": {
    id: 89,
    category: "Fortune",
    name: "Bounty Hunter",
    description:
      "When you kill a Mutation, gain 10 Copper (up to 300 per level)",
    filename: "bounty-hunter.jpg",
  },
  "90": {
    id: 90,
    category: "Fortune",
    name: "Ammo Stash",
    description:
      "Your secondary weapons have unlimited ammo. Your secondary weapons reload 20% slower",
    filename: "ammo-stash.jpg",
  },
  "91": {
    id: 91,
    category: "Fortune",
    name: "Life Insurance",
    description: "2 Extra lives, lose 50 Copper at the start of each level",
    filename: "life-insurance.jpg",
  },
  "92": {
    id: 92,
    category: "Fortune",
    name: "Wounded Animal",
    description: "Kills while at Critical Health recover 1 Health",
    filename: "wounded-animal.jpg",
  },
  "93": {
    id: 93,
    category: "Fortune",
    name: "Compound Interest",
    description: "Gain 10% of your total Copper in each Safe Room",
    filename: "compound-interest.jpg",
  },
  "94": {
    id: 94,
    category: "Fortune",
    name: "Lucky Pennies",
    description:
      "Whenever you or your team loots Copper, you have a 35% chance to find 35% additional Copper",
    filename: "lucky-pennies.jpg",
  },
  "95": {
    id: 95,
    category: "Fortune",
    name: "Money Grubbers",
    description:
      "Each time your team loots Copper, you gain 5 additional Copper stacking up to 100 additional Copper",
    filename: "money-grubbers.jpg",
  },
  "96": {
    id: 96,
    category: "Fortune",
    name: "Run and Gun",
    description: "You can shoot while sprinting",
    filename: "run-and gun.jpg",
  },
  "97": {
    id: 97,
    category: "Fortune",
    name: "Copper Scavenger",
    description: "You can sense nearby Copper, more Copper piles spawn",
    filename: "copper-scavenger.jpg",
  },
  "98": {
    id: 98,
    category: "Fortune",
    name: "Share the Wealth",
    description:
      "Each teammate gains 100 bonus Copper at the start of each level",
    filename: "share-the wealth.jpg",
  },
  "99": {
    id: 99,
    category: "Fortune",
    name: "Shell Carrier",
    description: "30% Shotgun Ammo Capacity, 10% Damage with Shotguns",
    filename: "shell-carrier.jpg",
  },
  "100": {
    id: 100,
    category: "Fortune",
    name: "Hazard Pay",
    description: "Gain 250 bonus Copper at the start of each level",
    filename: "hazard-pay.jpg",
  },
  "101": {
    id: 101,
    category: "Fortune",
    name: "Saferoom Recovery",
    description:
      "Your Team heals 5 Trauma Damage and refills 10% Ammo at the start of each level",
    filename: "saferoom-recovery.jpg",
  },
  "102": {
    id: 102,
    category: "Reflex",
    name: "Cross Trainers",
    description: "20% Stamina, 20% Stamina Regen, 3% Move Speed",
    filename: "cross-trainers.jpg",
  },
  "103": {
    id: 103,
    category: "Reflex",
    name: "Energy Drink",
    description: "40% Stamina, -5% Damage Resistance",
    filename: "energy-drink.jpg",
  },
  "104": {
    id: 104,
    category: "Reflex",
    name: "Rhythmic Breathing",
    description: "60% Stamina, -20% Slow Resistance",
    filename: "rhythmic-breathing.jpg",
  },
  "105": {
    id: 105,
    category: "Reflex",
    name: "Reload Drills",
    description: "20% Reload Speed",
    filename: "reload-drills.jpg",
  },
  "106": {
    id: 106,
    category: "Reflex",
    name: "Widemouth Magwell",
    description: "30% Reload Speed, -5% Damage Resistance",
    filename: "widemouth-magwell.jpg",
  },
  "107": {
    id: 107,
    category: "Reflex",
    name: "Mag Coupler",
    description: "50% Reload Speed, Disables: Aim Down Sights",
    filename: "mag-coupler.jpg",
  },
  "108": {
    id: 108,
    category: "Reflex",
    name: "Slugger",
    description:
      "5 Health, 10% Melee Stamina Efficiency, 20% Melee Attack Speed",
    filename: "slugger.jpg",
  },
  "109": {
    id: 109,
    category: "Reflex",
    name: "Brazen",
    description:
      "30% Melee Stamina Efficiency, 30% Melee Attack Speed, -5% Damage Resistance",
    filename: "brazen.jpg",
  },
  "110": {
    id: 110,
    category: "Reflex",
    name: "Meth Head",
    description:
      "40% Melee Attack Speed, 40% Melee Stamina Efficiency, Your Melee Attacks no longer stick in tough ene",
    filename: "meth-head.jpg",
  },
  "111": {
    id: 111,
    category: "Reflex",
    name: "Ridden Slayer",
    description: "20% Weakspot Damage",
    filename: "ridden-slayer.jpg",
  },
  "112": {
    id: 112,
    category: "Reflex",
    name: "Reckless Strategy",
    description: "30% Weakspot Damage, -5% Damage Resistance",
    filename: "reckless-strategy.jpg",
  },
  "113": {
    id: 113,
    category: "Reflex",
    name: "Hyper-Focused",
    description: "50% Weakspot Damage, -75% Aim Down Sight Move Speed",
    filename: "hyper-focused.jpg",
  },
  "114": {
    id: 114,
    category: "Reflex",
    name: "HI VIS Sights",
    description: "30% Aim Speed",
    filename: "hi-vis sights.jpg",
  },
  "115": {
    id: 115,
    category: "Reflex",
    name: "Tunnel Vision",
    description: "50% Aim Speed, -5% Damage Resistance",
    filename: "tunnel-vision.jpg",
  },
  "116": {
    id: 116,
    category: "Reflex",
    name: "Steady Aim",
    description: "80% Aim Speed, -50% Aim Down Sight Move Speed",
    filename: "steady-aim.jpg",
  },
  "117": {
    id: 117,
    category: "Reflex",
    name: "Shooting Gloves",
    description: "25% Weapon Swap Speed",
    filename: "shooting-gloves.jpg",
  },
  "118": {
    id: 118,
    category: "Reflex",
    name: "Guns Out",
    description: "50% Weapon Swap Speed, -5% Damage Resistance",
    filename: "guns-out.jpg",
  },
  "119": {
    id: 119,
    category: "Reflex",
    name: "Cocky",
    description:
      "75% Weapon Swap Speed, When you take damage, your Accuracy is reduced by 20% for 3 seconds",
    filename: "cocky.jpg",
  },
  "120": {
    id: 120,
    category: "Reflex",
    name: "Smelling Salts",
    description: "100% Revive Speed",
    filename: "smelling-salts.jpg",
  },
  "121": {
    id: 121,
    category: "Reflex",
    name: "Pep Talk",
    description: "150% Revive Speed, -5% Damage Resistance",
    filename: "pep-talk.jpg",
  },
  "122": {
    id: 122,
    category: "Reflex",
    name: "Rousing Speech",
    description:
      "225% Revive Speed, Disables: Offensive Accessories, Team Effects: 20% Reduced Incap Trauma",
    filename: "rousing-speech.jpg",
  },
  "123": {
    id: 123,
    category: "Reflex",
    name: "Dash",
    description: "5% Move Speed",
    filename: "dash.jpg",
  },
  "124": {
    id: 124,
    category: "Reflex",
    name: "Fleet of Foot",
    description: "10% Move Speed, -5% Damage Resistance",
    filename: "fleet-of foot.jpg",
  },
  "125": {
    id: 125,
    category: "Reflex",
    name: "Run Like Hell",
    description:
      "15% Move Speed, When you take damage, your Accuracy is reduced by 20% for 3 seconds",
    filename: "run-like hell.jpg",
  },
  "126": {
    id: 126,
    category: "Reflex",
    name: "Superior Cardio",
    description: "20% Stamina, 20% Sprint Efficiency, 5 Health",
    filename: "superior-cardio.jpg",
  },
  "127": {
    id: 127,
    category: "Reflex",
    name: "Olympic Sprinter",
    description: "30% Sprint Efficiency, -5% Damage Resistance",
    filename: "olympic-sprinter.jpg",
  },
  "128": {
    id: 128,
    category: "Reflex",
    name: "Reckless",
    description:
      "40% Sprint Efficiency, When you take damage while Sprinting, you lose all Stamina",
    filename: "reckless.jpg",
  },
  "129": {
    id: 129,
    category: "Reflex",
    name: "Breakout",
    description:
      "Breakout: Hold a button to free yourself from Grabs, 50% Breakout Cooldown Reduction (Base 60 seconds)",
    filename: "breakout.jpg",
  },
  "130": {
    id: 130,
    category: "Reflex",
    name: "Combat Medic",
    description:
      "50% Use Speed, Heals teammates for an additional 20 Health when you revive them",
    filename: "combat-medic.jpg",
  },
  "131": {
    id: 131,
    category: "Reflex",
    name: "Fire in the Hole!",
    description:
      "When you throw and Offensive Accessory, gain 20 Temporary Health and 20% Move Speed for 5 seconds",
    filename: "fire-in the hole!.jpg",
  },
  "132": {
    id: 132,
    category: "Reflex",
    name: "Medical Expert",
    description:
      "15% Healing Efficiency, When you use a Medical Accessory, you gain 15% Move Speed for 15 seconds",
    filename: "medical-expert.jpg",
  },
  "133": {
    id: 133,
    category: "Reflex",
    name: "Rolling Thunder",
    description:
      "35% Move Speed while firing with Shotguns, 10% Damage with Shotguns",
    filename: "rolling-thunder.jpg",
  },
  "134": {
    id: 134,
    category: "Reflex",
    name: "Speed Demon",
    description:
      "6% Move Speed while using an SMG, 35% Reload Speed while using an SMG",
    filename: "speed-demon.jpg",
  },
  "135": {
    id: 135,
    category: "Reflex",
    name: "Hellfire",
    description: "45% Move Speed while firing, 5% Move Speed while not firing",
    filename: "hellfire.jpg",
  },
  "136": {
    id: 136,
    category: "Reflex",
    name: "Marathon Runner",
    description:
      "No Movement Penalty for strafe and backpedal, Disables: Sprint",
    filename: "marathon-runner.jpg",
  },
  "137": {
    id: 137,
    category: "Reflex",
    name: "Mandatory PT",
    description: "Team Effects: 15% Team Stamina",
    filename: "mandatory-pt.jpg",
  },
  "138": {
    id: 138,
    category: "Reflex",
    name: "Pep In Your Step",
    description: "Precision Kills grant you 10% Move Speed for 5 seconds",
    filename: "pep-in your step.jpg",
  },
  "139": {
    id: 139,
    category: "Reflex",
    name: "Shredder",
    description:
      "Each bullet hit causes the target to take 1% increased damage for 3 seconds (stacks up to 15%)",
    filename: "shredder.jpg",
  },
  "140": {
    id: 140,
    category: "Reflex",
    name: "Glass Cannon",
    description: "25% Damage, -30% Health",
    filename: "glass-cannon.jpg",
  },
  "141": {
    id: 141,
    category: "Reflex",
    name: "Sadistic",
    description:
      "Gain 5% Weakspot Damage for each Precision Kill in the last 10 seconds",
    filename: "sadistic.jpg",
  },
  "142": {
    id: 142,
    category: "Reflex",
    name: "Evasive Action",
    description:
      "When you take a hit for 10 or more damage gain 20% Move Speed for 3 seconds",
    filename: "evasive-action.jpg",
  },
  "143": {
    id: 143,
    category: "Reflex",
    name: "Adrenaline Fueled",
    description:
      "100% Stamina, -75% Stamina Regeneration. When you kill an enemy, gain 10 Stamina instantly and an addit",
    filename: "adrenaline-fueled.jpg",
  },
  "144": {
    id: 144,
    category: "Reflex",
    name: "Miraculous Recovery",
    description:
      "When you use a Medical Accessory, it has a 25% chance to have 100% increased effect",
    filename: "miraculous-recovery.jpg",
  },
  "145": {
    id: 145,
    category: "Reflex",
    name: "Screwdriver",
    description: "50% Use Speed, 10% Stamina",
    filename: "screwdriver.jpg",
  },
  "146": {
    id: 146,
    category: "Reflex",
    name: "Multitool",
    description: "75% Use Speed, -5% Damage Resistance",
    filename: "multitool.jpg",
  },
  "147": {
    id: 147,
    category: "Reflex",
    name: "Headband Magnifier",
    description:
      "125% Use Speed. When you take damage, you have a chance to be blinded for 1 second",
    filename: "headband-magnifier.jpg",
  },
  "148": {
    id: 148,
    category: "Reflex",
    name: "Utility Scavenger",
    description:
      "You can sense nearby Quick Accessories. More Quick Accessories spawn",
    filename: "utility-scavenger.jpg",
  },
  "149": {
    id: 149,
    category: "Reflex",
    name: "Stimulants",
    description:
      "Pain meds you apply also grant 10% Move Speed, 10% Reload Speed, and 10% Weapon Swap Speed for 30 se",
    filename: "stimulants.jpg",
  },
  "150": {
    id: 150,
    category: "Reflex",
    name: "On Your Mark",
    description:
      "When you exit a starting safe room your team gains 15% Move Speed for 30 seconds",
    filename: "on-your mark.jpg",
  },
  "151": {
    id: 151,
    category: "Reflex",
    name: "Killer's Instinct",
    description: "30% Weakspot Damage, Disables: Aim Down Sights",
    filename: "killer's-instinct.jpg",
  },
  "152": {
    id: 152,
    category: "Reflex",
    name: "Power Swap",
    description:
      "Changing weapons within 0.75 seconds of reaching low ammo grants 20% Damage for 5 seconds",
    filename: "power-swap.jpg",
  },
  "153": {
    id: 153,
    category: "Reflex",
    name: "Stock Pouch",
    description: "30% Sniper Ammo Capacity, 10% Damage with Sniper Rifles",
    filename: "stock-pouch.jpg",
  },
  "154": {
    id: 154,
    category: "Reflex",
    name: "Mag Carrier",
    description:
      "30% Pistol/SMG Ammo Capacity, 10% Damage with Pistols and SMGs",
    filename: "mag-carrier.jpg",
  },
  "155": {
    id: 155,
    category: "Reflex",
    name: "Mad Dash",
    description: "20% Sprint Speed, 30% Sprint Stamina Efficiency",
    filename: "mad-dash.jpg",
  },
};
